#!/usr/bin/env ruby

require 'thread'
require 'socket'

def output(obj)
  puts obj
  $stdout.flush
end

def kill_everything
  output "Shutting Down!"
  exit
end

trap("INT") { kill_everything }
trap("HUP") { kill_everything }

begin
  if ARGV[0] == "--ssh"
    %x( ssh -t #{ARGV[1]} 'quickpasteclient' )
  else
    streamSock = TCPSocket.open("127.0.0.1", 6666)
    streamSock.puts(ARGV[0])
  end 
rescue
  @queue = Queue.new

  def threadCode 
    s = TCPServer.new(6666)
    while true
      client = s.accept
      @queue << client.recvmsg[0]
    end
  end

  @t = Thread.new {threadCode}

  output "Waiting for Pastes" 

  while true
    output @queue.pop
  end
end
